### ISSUE TITLE
problem with getting up and running

### ISSUE THREAD

**Issue by ashelley** [railsware/bozon#14]
- Windows 10
- node 4.4.4
- bozon 0.4.0

While trying to follow the install steps i do this:

1) bozon new helloworld
2) cd hello world
3) run npm install manually (for some reason this fails silently on my machine during the new process)
4) npm install fails because package.json contains a post install script 'install-app-deps'.  This fails because install-app-deps does not exist in ./node_modules/.bin

```
$ ls ./node_modules/.bin/
bozon*  bozon.cmd  electron*  electron.cmd
```

Any insight into how to complete the install is much appreciated.

**Comment by ashelley** [comment]
Oh.

I need to run `npm install -g electron-builder` first.  ooops.

Still working on a problem with 'bozon start' failing silently.

**Comment by ashelley** [comment]
Okay this issue can probably closed... I switched to using node 5.10.1 and npm version 3 (was previously using npm version 2.  Because of the way the gulp tasks are run I think the node modules tree must be flattened  so that gulp is always required as a singleton.

Sorry for the noise.

**Comment by alchapone** [comment]
@ashelley Yeah, was about to reply that I've tried to setup new app on Windows and it works as expected on newer version of node. Current version of `node` in Electron is `6.1.0`, so you should use same version in development as well.
