### ISSUE TITLE
bozon starts does not do anything and issue no errors

### ISSUE THREAD

**Issue by adriatic** [railsware/bozon#17]
I was very excited discovering bozon, after getting really tired searching for the best electron application skeleton. So, I followed your (very simple) installation guide, issued the command

```
bozon start
```
 and saw this:

```
C:\work\monterey-framework\generic-electron-app\generic_app (master)
λ bozon start

C:\work\monterey-framework\generic-electron-app\generic_app (master)
```

The first remedy I tried was to assume that your installation instructions should really be:
```
npm install -g bozon
bozon new [name]
npm install
```

however, while I believe that `npm install` should be run before `bozon start`, even after running `npm install` followed by `bozon start`, still nothing happend.

My last attempt was to install bozon locally to my project where I want to use it. No changes - `bozon start` does me as much good as pushing on my nose :-)

**My environment**
- windows 8.1
- node.js v5.1.1
- npm 3.5.0

Can you advise, please?

**Comment by alchapone** [comment]
Hey @adriatic! which bozon version are you using? Since v0.5.0 it is simply CLI tool which should be installed globally and you can work with different projects using global package. Are you reproducing this with most recent version?

**Comment by adriatic** [comment]
Hi @alchapone 

While my (globally installed) bozon does not seem willing to tell me it's version number:

```
λ bozon -v

  error: unknown option `-v'
```

(that should be a legal way to ask for the version number), the other way seems to work

```
λ bozon --version
0.5.0
```

I got bozon from npm registry (`https://www.npmjs.com/package/bozon`)

**Comment by alchapone** [comment]
I wonder if it has something to do with node version.. Could you try it with v.5.10.1?

**Comment by adriatic** [comment]
Well, yes, this issue does have something with node :-)

Installed the latest node (v6.2.2.) and run `bozon start` again:

```
λ bozon start
(node:4084) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[11:07:45] Using gulpfile C:\work\monterey-framework\generic-electron-app\gulpfile.js
[11:07:45] Starting 'html'...
[11:07:45] Starting 'images'...
[11:07:45] Starting 'styles'...
[11:07:45] Starting 'scripts:main'...
[11:07:45] Starting 'scripts:renderer'...
[11:07:49] Finished 'images' after 4.3 s
[11:07:49] Version: webpack 1.13.1
         Asset     Size  Chunks             Chunk Names
application.js  1.88 kB       0  [emitted]  main
[11:07:49] Finished 'styles' after 4.57 s
[11:07:49] Finished 'html' after 4.59 s
[11:07:49] Finished 'scripts:main' after 4.57 s
[11:07:49] Finished 'scripts:renderer' after 4.57 s
[11:07:49] Starting 'prepare:app'...
cp: cannot create directory `C:\\work\\monterey-framework\\generic-electron-app\\builds\\development/C:\\work\\monterey-framework\\generic-electron-app\\app\\node_modules': No such file or directory
[11:07:49] Finished 'prepare:app' after 303 ms
```

and 

![image](https://cloud.githubusercontent.com/assets/2712405/16308515/44c88794-3933-11e6-9a7a-32434679c511.png)

***

What is causing the error 
>cp: cannot create directory `C:\\work\\monterey-framework\\generic-electron-app\\builds\\development/C:\\work\\monterey-framework\\generic-electron-app\\app\\node_modules': No such file or directory

**Comment by alchapone** [comment]
Good, will add `node >= 5.10.1` to package.json and readme.. Error with `node_modules` doesn't impact application launch, but will work on fixing it in next version of `bozon`, thanks for feedback!

**Comment by adriatic** [comment]
Just to be very pedantic: we do not really have a proof that `node >= 5.10.1` is sufficient condition for bozon to run :-)

Thank you for creating bozon - I can see a lot of potential for it and will stay in touch to show you what all we will do with it :-)

**Comment by alchapone** [comment]
Well, I don't do thorough testing on windows, but I do test it on MacOS with node `5.10.1` :) Any kind of feedback is appreciated!
