### ISSUE TITLE
Native NPM Modules

### ISSUE THREAD

**Issue by MTRNord** [railsware/bozon#2]
Do Native NPM Modules work with this or do I need "electron-rebuild"?

**Comment by alchapone** [comment]
For now you need to user `electron-rebuild`, but probably it is good idea to support this within package

**Comment by develar** [comment]
@alchaplinsky electron-builder supports it. You can upgrade electron-builder to 12.0.3 to get this functionality.

**Comment by alchaplinsky** [comment]
Delegated to `electron-builder` since [v0.7.0](https://github.com/railsware/bozon/releases/tag/v0.7.0)
