### ISSUE TITLE
gulp isn't defined in ./lib/utils/bozon.js

### ISSUE THREAD

**Issue by alerdenisov** [railsware/bozon#21]
Missing requirement of gulp module in `./lib/utils/bozon.js`

**Comment by alchapone** [comment]
Is it present in `./node_modules` in your project directory?

**Comment by alerdenisov** [comment]
I mean you're using gulp variable without define it.. 
https://github.com/railsware/bozon/blob/master/lib/utils/bozon.js#L28

**Comment by klevinlaughs** [comment]
The requireLocal function returns a required instance of gulp. The function is defined it on line 37 of that file. Then he proceeds to use that instance.

**Comment by eriedl** [comment]
that is so not correct. while the apply function expects a "this argument", it cannot be inferred from the context it's called on. apply applies to functions not objects.
Lines 27 and 34 would have to look something like this:
`return this.requireLocal('gulp').task.apply(this.requireLocal('gulp'), Array.prototype.slice.call(arguments, 1))`
OR
`var gulp = this.requireLocal('gulp')
return gulp.task.apply(gulp, Array.prototype.slice.call(arguments, 1))`

**Comment by alchaplinsky** [comment]
Use version `v0.5.5`
