### ISSUE TITLE
How do you enable debugging for the Main Process?

### ISSUE THREAD

**Issue by hadees** [railsware/bozon#22]
[Debugging the Main Process](https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md)  in the electron docs talks about adding --debug but I can't seem to figure out how to do that with bozon.

**Comment by alchapone** [comment]
This is not currently supported, but it is a nice feature to add. Will focus on that in next release

**Comment by alchaplinsky** [comment]
[Added options](https://github.com/railsware/bozon/commit/0b93ac90eda1a17b51ec6d971088e901a5fd13c4) `--inspect` and `--inspect-brk`
