### ISSUE TITLE
Why do you need Webpack?

### ISSUE THREAD

**Issue by hadees** [railsware/bozon#24]
I've had some trouble getting native modules to load correctly in webpack.  I was curious why you used this instead of `electron-compile` and possibly `electron-connect`.

**Comment by alchapone** [comment]
@hadees Webpack is used to compile and bundle all javascript files including vendor libraries for renderer process.

**Comment by hadees** [comment]
@alchapone I understand that part of it but I was wondering why not use something else like [electron-compile](https://github.com/electron/electron-compile).  I've just had a lot of problems using `webpack` to load a native node module so I was hoping to try and use bozon but without `webpack`.

**Comment by alchapone** [comment]
What native module do you need in renderer process?

**Comment by hadees** [comment]
[WebChimera.js](https://github.com/RSATom/WebChimera.js)

**Comment by crystalOrigin** [comment]
@hadees if this is still an issue for you, check out [this solution](https://github.com/railsware/bozon/issues/40).

**Comment by hadees** [comment]
@crystalOrigin thanks!
