### ISSUE TITLE
Livereload Not Working

### ISSUE THREAD

**Issue by timkendall** [railsware/bozon#25]
Maybe I'm just being dumb but it doesn't seem like the app is auto-refreshing in development.

**Comment by alchapone** [comment]
@timkendall  Electron app scaffold does not come with livereload out of the box

**Comment by timkendall** [comment]
@alchapone Ahhh I see. The `reload` config option refers to the ability to Command + R the app. 

Would be nice to have this built in. If I get to it I'll put in a PR for having that available by default.
