### ISSUE TITLE
Can't use installed npm packages (the ones inside app/node_modules) (maybe a newby question)

### ISSUE THREAD

**Issue by h4ndshake** [railsware/bozon#30]
I'm on Windows 10, running Bozon 0.6.1

First of all, sorry, i'm a newbie at Javascript/NodeJS (this project itself is for learning more about it)

I've saved random-js and material-components-web to app/node_modules and I want to use them in my electron app, but the node_modules isn't being copied to the builds/development folder, so i cant use them.

Probably prepare::app can't stat them? 
I've see the routine for prepare::app, and (if i'm not wrong) Bozon will try to stat node_modules and copy it to the builds/<env>. And if it can't stat it, it will fallback to the cp -r method (wich is unavailable on Windows, of course), am I right?

And I don't know if this is a bug, or a stupid newbie question.. Thanks in advance

Cheers
![capturar](https://cloud.githubusercontent.com/assets/12601769/21290800/76c6b894-c4af-11e6-92ec-7512f1314dee.PNG)

**Comment by SirNeural** [comment]
I had the same problem, turns out it is because bozon is trying to use 'cp' to copy the files in node_modules, but since cp is a linux command, it fails and doesn't copy them over. I managed to fix this by installing cygwin and adding it to my path; that seemed to do the trick.

**Comment by alchaplinsky** [comment]
Fixed in v0.7.2
