### ISSUE TITLE
Creating Desktop Shortcut on Installation

### ISSUE THREAD

**Issue by dizawish** [railsware/bozon#34]
Is it possible to get a shortcut created on desktop on installation?

**Comment by alchaplinsky** [comment]
@dizawish On Windows, you mean?

**Comment by dizawish** [comment]
@alchaplinsky Yes. BTW script works like a charm.

**Comment by alchaplinsky** [comment]
I believe you should do it manually by defining squirrelWindows events.

**Comment by dizawish** [comment]
Thank you! I will try this and come back if i get it right to share.

**Comment by develar** [comment]
Default target for electron-builder now is nsis and shortcuts are created for you automatically. No more  special code or handlers in your app code.
