### ISSUE TITLE
Update electron-builder to 13.8.0

### ISSUE THREAD

**Issue by develar** [railsware/bozon#36]
1. Update electron-builder version to 13.8.0
2. Remove `electron-packager-tf` — not required anymore.

Is this project still alive? Should it be promoted on electron-builder page?

**Comment by alchaplinsky** [comment]
Of course it is! I haven't checked for recent versions of tools used in a while, though. Will take a look at `electron-builder` next then.

**Comment by alchaplinsky** [comment]
Update [done](https://github.com/railsware/bozon/releases/tag/v0.7.0)
