### ISSUE TITLE
config/platforms should contains options passed to electron builder

### ISSUE THREAD

**Issue by antonellopasella** [railsware/bozon#37]
Trying to package a portable windows app, I tought it will be enough to pass electron builder options into windwows.json but NSIS installer was produced

Any help?

{
  "icon": ".ico",
  "target": "portable"
}

Reference https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-target

**Comment by alchaplinsky** [comment]
`electron-builder` picks up options from `package.json`. So you can specify `"target": "portable"` in build section.
