### ISSUE TITLE
missing "bozon" in devDependencies

### ISSUE THREAD

**Issue by t-hofmann** [railsware/bozon#45]
How to reproduce:
- `bozon new PROJECT` (here under OSX)
- transfer project to linux (here via git push/pull) except for the `node_modules`-subdir
- `npm install` in the PROJECT's dir
- `bozon start`

That led to the error:
```
module.js:328
    throw err;
    ^

Error: Cannot find module 'bozon/lib/tasks'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/DIR/PROJECT/gulpfile.js:1:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
Error launching app
Unable to find Electron app at [...]
```
Fix:
in the file `PROJECT/package.json`
add to `devDependencies` 
the following dependency: 
`"bozon": "^0.7.1"`
and subsequently `npm install`

I found that as a solution since the module `bozon/lib/tasks` was in case of OSX found as `PROJECT/node_modules/bozon/lib/tasks.js` but missing in case of linux.

So "bozon" seems actually to be a missing devDependency.

HTH and kind regards,
Thomas

**Comment by JulioLopezN** [comment]
I had the same problem. I updated NodeJs to v8.1.2 and it worked fine.

**Comment by alchaplinsky** [comment]
Since `bozon` needs to be installed globally, use `npm link bozon` to link your global `bozon` into project directory.

**Comment by NicolaOrritos** [comment]
Why do I need to link the global version into my project?
I don't think this is fixed, more that a workaround has been found.

I had the same `Cannot find module 'bozon/lib/tasks'` error as @t-hofmann, on Windows 10, bozon 0.7.9.

**Comment by albertotorresfoltyn** [comment]
Can I cross build with bozon? Running on windows 10 x64 machine and this error happens when bozon package mac...

**Comment by alchaplinsky** [comment]
`bozon` has been added as dev dependencies in [v0.8.2](https://github.com/railsware/bozon/blob/v0.8.2/lib/templates/json/development_package.json#L10)
