### ISSUE TITLE
Unable to use whitespace in path

### ISSUE THREAD

**Issue by Lars-** [railsware/bozon#49]
When I create a program in a folder with a whitespace and I start it, I get the following error:
```
/bin/sh: 1: /home/lars/My: not found
/bin/sh: 1: /home/lars/My: not found
```
That's all. I just call `bozon start`.

The path: /home/lars/My Path/Test Project
OS: Ubuntu 17.10 (also happening on Mac OS High Sierra)

So what should I do?

**Comment by andrewo0** [comment]
@Lars- Your program name has to be without spaces.
after creating your program open package.json add "productName": "Test Project",
