### ISSUE TITLE
Typescript implementation

### ISSUE THREAD

**Issue by ndrantotiana** [railsware/bozon#51]
Hello everybody.

Happy new year.

This is not really an issue but a request for a "how-to" on how to use typescript as main language with bozon. I have an idea but it use "npm" not "bozon" and I don't know if it is the right way to do.

Thank you in advance.

**Comment by ndrantotiana** [comment]
I configured `gulpfile.js` to make the compilation and it's working fine now.

**Comment by umutc** [comment]
@ndrantotiana is there an example to see this implementation please?
