### ISSUE TITLE
Where modules for app/javascripts/main/index.js supposed to go?

### ISSUE THREAD

**Issue by artofvs** [railsware/bozon#56]
Steps:

1.  Created a new project with `bozon new bozontest`
2.  `cd bozontest/app` and `npm install electron-debug` to install package to the app/node_modules
3.  Added `require('electron-debug')();` to the app/javascripts/main/index.js
4.  Run `bozon start` from root project folder and it throws an error:
`App threw an error during load
Error: Cannot find module 'electron-debug'`

It works for packaged app, though.
Adding that package to the root package.json instead: works for `bozon start`, but does not work with packaged app.
Is it correct to add it to both root package.json and app/package.json ?

**Comment by alchaplinsky** [comment]
This should now work with single `package.json` file in root directory and all dependencies installed to `./node_modules` directory
