### ISSUE TITLE
Webpack config: is there a way to add more than two section(renderer,main) in the webpack.config.js?

### ISSUE THREAD

**Issue by umutc** [railsware/bozon#61]
Hello I need to add more than two section to the web pack config please help,

webpack.config.js
```
module.exports = {
  externals: ['electron', 'electron-store'],
  renderer: { ... },
  main: { ... },
  another: { ... }
  ...
};
```

**Comment by alchaplinsky** [comment]
Well, you can easily add as many sections as you need into `webpack.config.js` generated by bozon
