### ISSUE TITLE
No reloading for webpack

### ISSUE THREAD

**Issue by fredcox** [railsware/bozon#69]
Hi, 

I change the content in file main.js index.html and webpack not reloading

[bozon] [CHANGE] File src/main/index.js has been changed
[bozon] [~MAIN~] Compiled in 36 ms ✓
[bozon] [CHANGE] File src/renderer/index.html has been changed
[bozon] [RENDER] Compiling
[bozon] [RENDER] Compiled in 6 ms ✓

**Comment by alchaplinsky** [comment]
Hey @fredcox, did you try to run with `--reload` option?
`bozon start --reload` should re-compile and reload your app.

**Comment by fredcox** [comment]
Hi, i will try. thank u.
